server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # Set to true in production
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6
        multiplier: 1.1
  datasource:
    url: jdbc:postgresql://localhost:5432/dbs_catalog
    username: user
    password: secret
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

demobookshop:
  greeting: Hello, welcome to the local Demo Book Shop!