server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: order
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: secret
    url: r2dbc:postgresql://localhost:5432/dbs_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/dbs_order
  cloud:
    function:
      definition: dispatchOrder
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: ${spring.application.name}
        acceptOrder-out-0:
          destination: order-accepted
      rabbitmq:
        bindings:
          acceptOrder-out-0:
            producer:
              transacted: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: secret
    connection-timeout: 5s

demobookshop:
  catalog-service-uri: http://localhost:9001