version: "3"
services:
  catalog:
    build: .
    image: catalog
    depends_on:
      - postgres
    ports:
      - "9001:9001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dbs_catalog
      - SPRING_PROFILES_ACTIVE=testdata
  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dbs_catalog
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
