version: "3"
services:
  catalog:
    build: ../../catalog
    image: catalog
    depends_on:
      - postgres
    ports:
      - "9001:9001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dbs_catalog
      - SPRING_PROFILES_ACTIVE=testdata
  order:
    build: ../../order
    image: order
    depends_on:
      - postgres
    ports:
      - "9002:9002"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/dbs_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/dbs_order
      - DEMOBOOKSHOP_CATALOG_SERVICE_URI=http://catalog:9001
  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
  edge-service:
    build: ../../edge-service
    image: edge-service
    ports:
      - "9000:9000"
    environment:
      - CATALOG_SERVICE_URL=http://catalog:9001
      - ORDER_SERVICE_URL=http://order:9002

